In [35]:
import pandas as pd
import numpy as np

In [36]:
df = pd.read_csv('선박입출항.csv', encoding='cp949')
df[df['선박종류명'] == '풀컨테이너선']

,청코드,선박키,입항연도,입항회수,업체코드,업체명,차항지코드1,차항지코드2,차항지명,적재톤수,...,출항예정일시,전출항지출항일시,전출항지코드1,전출항지코드2,전출항지명,입항일시,출항일시,양하톤수,선원수,전체승객수
0,20,9256391,2019,2,KMC2009,벤라인에이전시즈코리아주식회사,CN,DLC,DALIAN,6773.0,...,2019-10-18 15:00,2019-10-15 11:00,CN,DLC,DALIAN,2019-10-17 14:00,2019-10-18 14:00,6773.0,22.0,NaN
7,20,920990,2019,45,OSL0038,장금상선(주),JP,MYJ,MATSUYAMA,1281.0,...,2019-06-30 12:00,2019-06-28 20:00,JP,MYJ,MATSUYAMA,2019-06-29 14:12,2019-07-01 02:36,1281.0,20.0,NaN
8,20,DSEN8,2019,48,KMS8833,남성해운(주),JP,HKT,HAKATA/FUKUOKA,2100.0,...,2019-06-27 20:00,2019-06-26 10:00,JP,HSM,HOSOSHIMA,2019-06-27 11:45,2019-06-27 21:15,2100.0,16.0,NaN
10,20,D7QE,2019,71,KMS8831,흥아해운(주),JP,MOJ,MOJI/KITAKYUSHU,798.0,...,2019-06-27 22:12,2019-06-26 22:00,JP,HKT,HAKATA/FUKUOKA,2019-06-27 07:23,2019-06-27 22:12,798.0,14.0,NaN
11,20,9400095,2019,5,KMC0360,하파그로이드코리아(주),CN,NGB,NINGBO,36400.0,...,2019-07-04 14:00,2019-07-01 13:00,JP,YOK,YOKOHAMA,2019-07-03 20:00,2019-07-04 13:00,17736.0,20.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272437,20,DSEX8,2024,63,KMS8832,고려해운(주),KR,USN,울산,536.0,...,2024-08-23 0:00,2024-08-21 11:30,JP,HIJ,HIROSHIMA,2024-08-22 11:48,2024-08-23 00:06,536.0,15.0,NaN
272439,20,DDDI2,2024,2,BSC0406,오케이쉬핑(주),CN,SHA,SHANGHAI,6524.0,...,2024-08-10 1:18,2024-07-27 8:00,US,LAX,LOSANGELES,2024-08-09 16:25,2024-08-10 01:18,0.0,23.0,NaN
272441,20,9383534,2024,33,KMS8832,고려해운(주),KR,USN,울산,1779.0,...,2024-08-24 0:00,2024-08-22 18:00,JP,TKY,TOKUYAMA,2024-08-23 11:12,2024-08-24 03:54,1779.0,18.0,NaN
272443,20,A8JK4,2024,8,KMS8832,고려해운(주),CN,SHA,SHANGHAI,13325.0,...,2024-08-25 9:00,2024-08-21 8:30,CN,SHK,SHEKOU PT,2024-08-24 14:40,2024-08-25 12:50,9392.0,22.0,NaN
272816,20,9976587,2024,1,BSZ9227,(주)에이치제이중공업,KR,ZZZ,기타항,0.0,...,2024-09-30 0:00,2024-07-15 0:00,KR,ZZZ,기타항,2024-07-16 00:00,2025-01-22 09:00,0.0,125.0,0.0

In [37]:
df['출항예정일시'] = pd.to_datetime(df['출항예정일시'], errors='coerce')
df['출항일시'] = pd.to_datetime(df['출항일시'], errors='coerce')

df['출항차이시간'] = (
    df['출항일시'] - df['출항예정일시']
).dt.total_seconds() / 3600

In [38]:
df[['업체코드', '차항지명', '적재톤수', '입항일시','출항예정일시','출항일시','양하톤수','출항차이시간','선박종류명']]

,업체코드,차항지명,적재톤수,입항일시,출항예정일시,출항일시,양하톤수,출항차이시간,선박종류명
0,KMC2009,DALIAN,6773.0,2019-10-17 14:00,2019-10-18 15:00:00,2019-10-18 14:00:00,6773.0,-1.000000,풀컨테이너선
1,BSC0003,TAIXING,0.0,2019-10-15 19:00,2019-10-16 09:00:00,2019-10-16 10:00:00,0.0,1.000000,LPG 운반선
2,BSC2172,포항,4093.0,2019-10-14 06:00,2019-10-15 18:00:00,2019-10-14 16:00:00,4093.0,-26.000000,일반화물선
3,BSK2533,옥포,0.0,2019-09-26 15:50,2019-10-08 05:35:00,2019-10-08 05:35:00,0.0,0.000000,석유제품 운반선
4,KMC0823,SHIDAO PT,313.0,2019-06-26 20:00,2019-06-27 12:00:00,2019-06-27 12:00:00,313.0,0.000000,세미(혼재)컨테이너선
...,...,...,...,...,...,...,...,...,...
272899,BSZ7572,기타항,0.0,2023-09-11 13:05,2023-09-12 12:00:00,2023-09-19 15:25:00,0.0,171.416667,기타 예선
272900,BSZ7572,기타항,0.0,2023-11-03 08:37,2023-11-04 12:00:00,2023-12-04 08:54:00,0.0,716.900000,기타 예선
272901,BSZ7572,기타항,0.0,2023-12-04 16:05,2023-12-05 12:00:00,2023-12-04 16:06:00,0.0,-19.900000,기타 예선
272902,BSZ3389,기타항,0.0,2023-12-27 08:55,2023-12-28 12:00:00,2024-01-04 11:25:00,0.0,167.416667,견인용예선
272903,NaN,NaN,NaN,2022-12-26 00:00,NaT,2023-01-09 00:00:00,NaN,NaN,공사(작업)용 부선

In [39]:
df = df[df['출항차이시간'] > 0]
df

,청코드,선박키,입항연도,입항회수,업체코드,업체명,차항지코드1,차항지코드2,차항지명,적재톤수,...,전출항지출항일시,전출항지코드1,전출항지코드2,전출항지명,입항일시,출항일시,양하톤수,선원수,전체승객수,출항차이시간
1,20,3FNH6,2019,3,BSC0003,(주)반도마리타임,CN,TAX,TAIXING,0.0,...,2019-10-15 14:00,KR,USN,울산,2019-10-15 19:00,2019-10-16 10:00:00,0.0,16.0,NaN,1.000000
6,20,170032,2019,1,BSM0186,부광,KR,ZZZ,기타항,0.0,...,2019-03-15 09:50,KR,ZZZ,기타항,2019-03-15 14:20,2019-03-18 09:50:00,0.0,1.0,0.0,0.333333
7,20,920990,2019,45,OSL0038,장금상선(주),JP,MYJ,MATSUYAMA,1281.0,...,2019-06-28 20:00,JP,MYJ,MATSUYAMA,2019-06-29 14:12,2019-07-01 02:36:00,1281.0,20.0,NaN,14.600000
8,20,DSEN8,2019,48,KMS8833,남성해운(주),JP,HKT,HAKATA/FUKUOKA,2100.0,...,2019-06-26 10:00,JP,HSM,HOSOSHIMA,2019-06-27 11:45,2019-06-27 21:15:00,2100.0,16.0,NaN,1.250000
16,20,939577,2019,9,BSC2130,에이치알쉬핑(주),JP,FNB,FUNABASHI,3042.0,...,2019-08-16 12:00,KR,TJI,당진,2019-08-18 17:00,2019-08-18 23:47:00,0.0,13.0,NaN,1.783333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272894,20,D9SV,2023,22,BSZ3389,해강선박,KR,ZZZ,기타항,0.0,...,2023-11-30 15:55,KR,ZZZ,기타항,2023-12-04 14:20,2023-12-05 16:54:00,0.0,2.0,0.0,4.900000
272897,20,D9SV,2023,25,BSZ3389,해강선박,KR,ZZZ,기타항,0.0,...,2023-12-14 9:45,KR,ZZZ,기타항,2023-12-23 11:15,2023-12-27 06:45:00,0.0,2.0,0.0,66.750000
272899,20,785874,2023,15,BSZ7572,금성호,KR,ZZZ,기타항,0.0,...,2023-08-07 9:10,KR,ZZZ,기타항,2023-09-11 13:05,2023-09-19 15:25:00,0.0,1.0,0.0,171.416667
272900,20,785874,2023,16,BSZ7572,금성호,KR,ZZZ,기타항,0.0,...,2023-08-07 9:10,KR,ZZZ,기타항,2023-11-03 08:37,2023-12-04 08:54:00,0.0,1.0,0.0,716.900000
272902,20,D9SV,2023,26,BSZ3389,해강선박,KR,ZZZ,기타항,0.0,...,2023-12-18 13:10,KR,ZZZ,기타항,2023-12-27 08:55,2024-01-04 11:25:00,0.0,2.0,0.0,167.416667

In [40]:
df_container = df[df['선박종류명'] == '풀컨테이너선']
df_container

,청코드,선박키,입항연도,입항회수,업체코드,업체명,차항지코드1,차항지코드2,차항지명,적재톤수,...,전출항지출항일시,전출항지코드1,전출항지코드2,전출항지명,입항일시,출항일시,양하톤수,선원수,전체승객수,출항차이시간
7,20,920990,2019,45,OSL0038,장금상선(주),JP,MYJ,MATSUYAMA,1281.0,...,2019-06-28 20:00,JP,MYJ,MATSUYAMA,2019-06-29 14:12,2019-07-01 02:36:00,1281.0,20.0,NaN,14.600000
8,20,DSEN8,2019,48,KMS8833,남성해운(주),JP,HKT,HAKATA/FUKUOKA,2100.0,...,2019-06-26 10:00,JP,HSM,HOSOSHIMA,2019-06-27 11:45,2019-06-27 21:15:00,2100.0,16.0,NaN,1.250000
41,20,3EKA7,2019,6,ICC2115,오션네트워크익스프레스코리아(주),PA,MIT,MANZANILLO,55378.0,...,2019-07-04 01:00,CN,YAN,YANGSHAN,2019-07-05 14:06,2019-07-06 11:10:00,10075.0,22.0,NaN,2.166667
57,20,A8JS9,2019,27,KMC8410,범주해운(주),JP,HIJ,HIROSHIMA,3000.0,...,2019-07-06 01:00,KR,USN,울산,2019-07-06 11:10,2019-07-08 23:00:00,2334.0,15.0,NaN,4.000000
64,20,C6OW2,2019,8,KMS8833,남성해운(주),JP,HIC,HITACHINAKA,3000.0,...,2019-07-04 16:00,JP,OTK,OTAKE,2019-07-06 00:15,2019-07-06 12:36:00,3000.0,15.0,NaN,4.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272429,20,DSFS5,2024,46,KMS8832,고려해운(주),JP,HIJ,HIROSHIMA,1073.0,...,2024-08-20 14:00,JP,SEN,SATSUMASENDAI,2024-08-21 05:54,2024-08-22 05:48:00,1073.0,15.0,NaN,8.800000
272437,20,DSEX8,2024,63,KMS8832,고려해운(주),KR,USN,울산,536.0,...,2024-08-21 11:30,JP,HIJ,HIROSHIMA,2024-08-22 11:48,2024-08-23 00:06:00,536.0,15.0,NaN,0.100000
272441,20,9383534,2024,33,KMS8832,고려해운(주),KR,USN,울산,1779.0,...,2024-08-22 18:00,JP,TKY,TOKUYAMA,2024-08-23 11:12,2024-08-24 03:54:00,1779.0,18.0,NaN,3.900000
272443,20,A8JK4,2024,8,KMS8832,고려해운(주),CN,SHA,SHANGHAI,13325.0,...,2024-08-21 8:30,CN,SHK,SHEKOU PT,2024-08-24 14:40,2024-08-25 12:50:00,9392.0,22.0,NaN,3.833333
272816,20,9976587,2024,1,BSZ9227,(주)에이치제이중공업,KR,ZZZ,기타항,0.0,...,2024-07-15 0:00,KR,ZZZ,기타항,2024-07-16 00:00,2025-01-22 09:00:00,0.0,125.0,0.0,2745.000000

In [51]:
df = df_container[
    (df_container['출항차이시간'] > 1) &
    (df_container['출항차이시간'] < 72)
]
df

,청코드,선박키,입항연도,입항회수,업체코드,업체명,차항지코드1,차항지코드2,차항지명,적재톤수,...,전출항지출항일시,전출항지코드1,전출항지코드2,전출항지명,입항일시,출항일시,양하톤수,선원수,전체승객수,출항차이시간
7,20,920990,2019,45,OSL0038,장금상선(주),JP,MYJ,MATSUYAMA,1281.0,...,2019-06-28 20:00,JP,MYJ,MATSUYAMA,2019-06-29 14:12,2019-07-01 02:36:00,1281.0,20.0,NaN,14.600000
8,20,DSEN8,2019,48,KMS8833,남성해운(주),JP,HKT,HAKATA/FUKUOKA,2100.0,...,2019-06-26 10:00,JP,HSM,HOSOSHIMA,2019-06-27 11:45,2019-06-27 21:15:00,2100.0,16.0,NaN,1.250000
41,20,3EKA7,2019,6,ICC2115,오션네트워크익스프레스코리아(주),PA,MIT,MANZANILLO,55378.0,...,2019-07-04 01:00,CN,YAN,YANGSHAN,2019-07-05 14:06,2019-07-06 11:10:00,10075.0,22.0,NaN,2.166667
57,20,A8JS9,2019,27,KMC8410,범주해운(주),JP,HIJ,HIROSHIMA,3000.0,...,2019-07-06 01:00,KR,USN,울산,2019-07-06 11:10,2019-07-08 23:00:00,2334.0,15.0,NaN,4.000000
64,20,C6OW2,2019,8,KMS8833,남성해운(주),JP,HIC,HITACHINAKA,3000.0,...,2019-07-04 16:00,JP,OTK,OTAKE,2019-07-06 00:15,2019-07-06 12:36:00,3000.0,15.0,NaN,4.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272401,20,3EHD2,2024,11,OSL2001,에스엠상선(주)부산영업소,US,LGB,LONGBEACH,36569.0,...,2024-08-10 8:00,CN,NGB,NINGBO,2024-08-11 18:06,2024-08-12 12:40:00,4811.0,20.0,NaN,1.666667
272418,20,9850836,2024,2,KMC0123,(주)에버그린코리아,PA,BLB,BALBOA,80159.0,...,2024-08-10 5:00,CN,NGB,NINGBO,2024-08-13 02:00,2024-08-14 05:05:00,138.0,23.0,2.0,3.083333
272429,20,DSFS5,2024,46,KMS8832,고려해운(주),JP,HIJ,HIROSHIMA,1073.0,...,2024-08-20 14:00,JP,SEN,SATSUMASENDAI,2024-08-21 05:54,2024-08-22 05:48:00,1073.0,15.0,NaN,8.800000
272441,20,9383534,2024,33,KMS8832,고려해운(주),KR,USN,울산,1779.0,...,2024-08-22 18:00,JP,TKY,TOKUYAMA,2024-08-23 11:12,2024-08-24 03:54:00,1779.0,18.0,NaN,3.900000
272443,20,A8JK4,2024,8,KMS8832,고려해운(주),CN,SHA,SHANGHAI,13325.0,...,2024-08-21 8:30,CN,SHK,SHEKOU PT,2024-08-24 14:40,2024-08-25 12:50:00,9392.0,22.0,NaN,3.833333